packages:
  - .
  - playground
catalog:
  '@iconify-json/ri': ^1.2.5
  '@iconify/tools': ^4.1.2
  '@iconify/types': '*'
  '@ntnyq/eslint-config': ^4.1.0
  '@ntnyq/prettier-config': ^2.0.0
  '@ntnyq/utils': ^0.6.4
  '@types/node': ^22.15.2
  '@unocss/reset': ^66.1.0-beta.12
  '@vitejs/plugin-vue': ^5.2.3
  '@vueuse/core': ^13.1.0
  bumpp: ^10.1.0
  consola: ^3.4.2
  eslint: ^9.25.1
  husky: ^9.1.7
  nano-staged: ^0.8.0
  npm-run-all2: ^7.0.2
  prettier: ^3.5.3
  tinyexec: ^1.0.1
  tinyglobby: ^0.2.13
  tsx: ^4.19.3
  typescript: ^5.8.3
  uncase: ^0.1.0
  unocss: ^66.1.0-beta.12
  vite: ^6.3.3
  vue: ^3.5.13
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - esbuild
